---
tags: [rest]
projects: [spring-framework]
---
:spring_version: current
:toc:
:project_id: gs-rest-service
:spring_version: current
:spring_boot_version: 1.3.0.M4
:icons: font
:source-highlighter: prettify

This solution provides a template "Hello World" RESTful web service with Spring. 

The "Hello World"-iness goes well beyond what the web services does, rather it extends to all ways of working and includes matters such as exposing basic production-ready monitoring features.

Key template aspects include:

* "Inversion of Container" using https://github.com/spring-projects/spring-boot[Spring Boot] with Tomcat 8 as embedded servlet container.
* https://maven.apache.org/surefire/maven-surefire-plugin/[maven-surefire-plugin] driven unit testing.
* https://maven.apache.org/surefire/maven-failsafe-plugin/[maven-failsafe-plugin] driven integration testing utilising https://github.com/spring-projects/spring-boot[Spring Boot] http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/IntegrationTest.html[@IntegrationTest] and the https://github.com/jayway/rest-assured[rest-assured] REST testing library.
* Health endpoint exposure using http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready[spring-boot-starter-actuator]. 
* An idempotent greetings service and so intentional use of HTTP GET given that responses are cacheable by proxies with HTTP GET.

== What the template provides

The template project both provides and integration tests a service that will accept HTTP GET requests at:

----
1. http://localhost:8080/greetings
2. http://localhost:8080/greetings/{name}
3. http://localhost:8080/health
----

and in the case of the greetings end points respond with a JSON representation of a greeting:

[source,json]
----
{"id":1,"content":"Hello, World!"}
----

You can customize the greeting with an optional `name` URL parameter:

----
http://localhost:8080/greetings/User
----

The `name` parameter value overrides the default value of "World" and is reflected in the response:

[source,json]
----
{"id":1,"content":"Hello, User!"}
----

The health endpoint

----
http://localhost:8080/health
----

responds with for example:

[source,json]
----
{"status":"UP"}
----

== What the template builds on

This template project is a fork of the guide https://github.com/spring-guides/gs-rest-service[gs-rest-service] which you are advised to consult for guidance.