---
tags: [rest]
projects: [spring-framework]
---
:spring_version: current
:toc:
:project_id: gs-rest-service
:spring_version: current
:spring_boot_version: 1.3.0.M4
:icons: font
:source-highlighter: prettify

This solution provides a template "hello world" RESTful web service with Spring. Key template aspects include:

* "Invertion of Container" using https://github.com/spring-projects/spring-boot[Spring Boot] with Tomcat 8 as embedded servlet container.
* maven-surefire-plugin driven unit testing.
* maven-failsafe-plugin driven integration testing utilising https://github.com/spring-projects/spring-boot[Spring Boot] @IntegrationTest and the rest-assured REST testing library.
* Health endpoint exposure using spring-boot-starter-actuator. 
* An idempotent greetings service as so intentional use of HTTP GET given that responses that are cacheable by proxies with HTTP GET.

== What the template provides

The template project both provides and integration tests a service that will accept HTTP GET requests at:

----
1. http://localhost:8080/greetings
2. http://localhost:8080/greetings/{name}
3. http://localhost:8080/health
----

and in the case of the greetings end points respond with a JSON representation of a greeting:

[source,json]
----
{"id":1,"content":"Hello, World!"}
----

You can customize the greeting with an optional `name` parameter in the query string:

----
http://localhost:8080/greetings/User
----

The `name` parameter value overrides the default value of "World" and is reflected in the response:

[source,json]
----
{"id":1,"content":"Hello, User!"}
----

The health endpoint

----
http://localhost:8080/health
----

responds with for example:

[source,json]
----
{"status":"UP"}
----

== What the template builds on

This template project is a fork of the guide https://github.com/spring-guides/gs-rest-service[gs-rest-service] which you are advised to consult for guidance.